### ISSUE TITLE
Знайти питання до захисту лабароторної №8

### ISSUE THREAD

**Issue by KingKong007** [KingKong007/project#1]

**Comment by KingKong007** [comment]
![image](https://cloud.githubusercontent.com/assets/26644217/24333819/d9a0b6d0-1267-11e7-8508-52b3bb9c8338.png)

**Comment by KingKong007** [comment]
![image](https://cloud.githubusercontent.com/assets/26644217/24333831/04c4fd80-1268-11e7-85b4-c6dab7f107c2.png)

**Comment by katisergio** [comment]
Гарне зображення.
Відповіді уже знайдені.

**Comment by KingKong007** [comment]
![mhgf3ktw5t8](https://cloud.githubusercontent.com/assets/26644217/24334058/18f7fe3e-126c-11e7-8248-d0976f4d75d6.jpg)
